### ISSUE TITLE
Can't get admin access

### ISSUE THREAD

**Issue by IshfaqKhawaja** [Nabia-Sheikh/hotel-management-admin#1]
How can i get admin access, i want to start a similar project, if you can give me admin access, I want to log into admin account to check if this is perfect boiler plate code for me.
Reachout to me at [ishfaqkhawaja312@gmail.com](mailto:ishfaqkhawaja312@gmail.com)

**Comment by Nabia-Sheikh** [comment]
updated, check readme.
